### ISSUE TITLE
Update to version 217 to support Android Q

### ISSUE THREAD

**Issue by mijorus** [KiralyCraft/callrecorder-axet#2]
I did it already on my repo if someone cant wait 
https://github.com/mijorus/callrecorder-axet/tree/217

**Comment by KiralyCraft** [comment]
Glad you mentioned it, I'll find a way to make it auto-download the latest version, so the module zip itself stays the same. Totally forgot, whoopsie

**Comment by KiralyCraft** [comment]
Forgot again, but i've updated it now, to 1.7.13
