### ISSUE TITLE
Call recorder crashes frequently

### ISSUE THREAD

**Issue by Karan688** [KiralyCraft/callrecorder-axet#4]
The call recorder app crashes frequently when making calls using on android 9, version 1.7.13(219)
Log `attached
[Axetlog.txt](https://github.com/KiralyCraft/callrecorder-axet/files/5971275/Axetlog.txt)

**Comment by KiralyCraft** [comment]
Unfortunately, there is not much I can do. This is just a Magisk module wrapping the app. Please report this to the devs, and make sure you're running the latest version. See the links in the README for more details

**Comment by Karan688** [comment]
Wrong destination
